Account for reserved connections
sensu-plugins/sensu-plugins-postgres pull request #34
Opened 2017-07-13 19:24 UTC by Evesy

## Pull Request Checklist

RE https://github.com/sensu-plugins/sensu-plugins-postgres/issues/16

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets

- [x] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose

As per https://github.com/sensu-plugins/sensu-plugins-postgres/issues/16 `check-postgres-connections.rb` does not account for reserved superuser connections when calculating/displaying available connections.

This PR subtracts reserved connections from the total before calculating available connections, to give a more accurate result.

#### Known Compatablity Issues

2017-07-14 23:08 UTC, majormoses commented
@Evesy this looks good, I see conflicts and I need a test of some kind (unit is preferable), other forms would be a gist of input and output.

2017-07-14 23:09 UTC, majormoses requested changes
Looks, good, but have conflicts, while you are at it can you provide a testing artifact?

2017-07-25 19:41 UTC, Evesy commented
Rebase went a bit funky...

Also built & run against a postgres DB:

```
postgres=# show max_connections;
 max_connections
-----------------
 100
(1 row)


postgres=# show superuser_reserved_connections;
 superuser_reserved_connections
--------------------------------
 3
(1 row)

postgres=# SELECT count(*) from pg_stat_activity;
 count
-------
     1
(1 row)
```


```
[root@postgres001 ~]# /opt/sensu/embedded/bin/check-postgres-connections.rb -h 127.0.0.1 -u postgres -p <password> -a
CheckPostgresConnections OK: PostgreSQL connections under threshold: 1%, 1 out of 97 connections
```

2017-07-26 04:25 UTC, majormoses approved these changes

2017-07-26 04:27 UTC, merged

2017-07-26 04:28 UTC, majormoses commented
@Evesy ya the history was pretty messed up I tried to fix it up best I could to get it mergeable.

2017-07-26 04:37 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-postgres/versions/1.3.0