Move common methods to library
sensu-plugins/sensu-plugins-postgres pull request #56
Opened 2018-10-07 06:30 UTC by phumpal

## Pull Request Checklist

Related to https://github.com/sensu-plugins/sensu-plugins-postgres/pull/53#discussion_r189150535

#### General

- [x] Update Changelog following the conventions laid out  [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

#### Known Compatibility Issues

2018-10-11 05:19 UTC, majormoses commented
Sorry for the delay I have been traveling for work, will review shortly.

2018-10-11 05:20 UTC, majormoses commented
You can ignore that CI failure, its a known issue and I will drop ruby 2.1 support this weekend.

2018-10-11 05:23 UTC, majormoses requested changes

2018-10-11 05:23 UTC, majormoses commented on lib/sensu-plugins-postgres/pgutil.rb
> +  def check_vsn(conn)
Since this does not actually return the version back maybe we should call it `postgres9?` as it returns only a true if its a postgres 9 and false if it's either greater than 10 or lower than 8. Perhaps we should update the logic to reflect?

2018-10-11 05:23 UTC, majormoses commented on lib/sensu-plugins-postgres/pgutil.rb
> +    Gem::Version.new(pg_vsn) < Gem::Version.new('10.0') && Gem::Version.new(pg_vsn) >= Gem::Version.new('9.0')
I think we should also add a conditional to make sure that prior to version 8

2018-10-12 05:12 UTC, phumpal commented on lib/sensu-plugins-postgres/pgutil.rb
> +  def check_vsn(conn)
Wasn't PG 8 EOL in 2014? https://www.postgresql.org/support/versioning/

2018-10-12 05:12 UTC, phumpal commented
> Sorry for the delay I have been traveling for work, will review shortly.

No worries; work life balance is important :)

2018-10-12 20:42 UTC, phumpal commented on lib/sensu-plugins-postgres/pgutil.rb
> +    Gem::Version.new(pg_vsn) < Gem::Version.new('10.0') && Gem::Version.new(pg_vsn) >= Gem::Version.new('9.0')
IIRC PostgreSQL 8 is EOL https://endoflife.software/applications/databases/postgresql

2018-10-16 00:49 UTC, majormoses commented on lib/sensu-plugins-postgres/pgutil.rb
> +  def check_vsn(conn)
ok then how about `newer_postgres9?` I just want the name of the function to match what its actually doing, `check_version` is ambiguous in what its checking.

2018-10-16 01:40 UTC, phumpal commented on lib/sensu-plugins-postgres/pgutil.rb
> +  def check_vsn(conn)
:+1: will do

2018-10-16 17:22 UTC, phumpal commented
@majormoses updated. PTAL

2018-10-17 02:27 UTC, majormoses approved these changes

2018-10-17 02:28 UTC, merged

2018-10-17 02:37 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-postgres/versions/2.1.0