Fix metric-postgres-graphite.rb replication function names for PostgreSQL 10.x+
sensu-plugins/sensu-plugins-postgres pull request #69
Opened 2018-11-05 06:31 UTC by jfineberg

## Pull Request Checklist

This will address Issue #52 and provide graphite metrics support in PostgreSQL 10.x+

Refactor metric-postgres-graphite.rb to operate like check-postgres-replication.rb using common methods provided in lib.

-- performs a version check and uses the appropriate function names for getting replication status.

2018-11-08 02:25 UTC, majormoses requested changes
Hey thanks for picking this back up, I think it looks good can you show the input and output of the check demonstrating the fix? I don't run postgres so I don't have somewhere to easily test some of the features. Couple of comments but otherwise looks good.

2018-11-08 02:25 UTC, majormoses commented on bin/metric-postgres-graphite.rb
> +  option :ssl,
adding this new option should be called out in the changelog  in a `### Added` header.

2018-11-08 02:25 UTC, majormoses commented on bin/metric-postgres-graphite.rb
> +         short: '-S',
I think this should be `-S VALUE`

2018-11-08 02:25 UTC, majormoses commented on bin/metric-postgres-graphite.rb
> +         long: '--ssl',
I think this should be `--ssl VALUE`

2018-11-09 21:12 UTC, phumpal commented
>  I think it looks good can you show the input and output of the check demonstrating the fix

@jfineberg do you need help with this. Would love to see this merged!

2018-12-17 05:01 UTC, phumpal commented
@jfineberg gentle ping.

2019-03-08 23:01 UTC, phumpal commented
@majormoses FYI

> I think it looks good can you show the input and output of the check demonstrating the fix

Using PostgreSQL 11

```
sensu@postgres-main-slave:~$ metric-postgres-graphite.rb -d airbrake_development -m 10.2.13.11 -s 10.2.3.9 -uairbrake -pairbrake -P 6543
postgres-main-slave.postgres.replication_lag 0 1552085400
```

2019-03-12 03:44 UTC, majormoses commented
This looks good, I will work on merging and cutting a release shortly. @phumpal thank you for once again being my postgres savior for getting stuff over the line! just a friendly reminder that putting your DB credentials on the CLI like that exposes the credentials to the process table making it accessible to any user on the system. It's is recommended that you either supply an env var to the sensu process, use token substitution, or do something like this:
```
metric-postgres-graphite.rb -d airbrake_development -m 10.2.13.11 -s 10.2.3.9 -u$(cat my_db_username_file) -p$(my_database_password_file) -P 6543
```

2019-03-12 07:09 UTC, phumpal commented
> This looks good, I will work on merging and cutting a release shortly

:+1:

> thank you for once again being my postgres savior for getting stuff over the line!

Of course. Happy to help!

> It's is recommended that you either supply an env var 

My dev environment thanks you ;)

2019-03-12 07:18 UTC, majormoses approved these changes

2019-03-12 07:18 UTC, merged

2019-03-12 07:29 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-postgres/versions/2.3.2

2019-03-12 17:17 UTC, phumpal commented
🍻 thanks!